insert into USER(id, name, priority) values(1, 'Nicolas B.', 1);
insert into USER(id, name, priority) values(2, 'Geoffroy', 5);
insert into USER(id, name, priority) values(3, 'Alain', 10);
insert into USER(id, name, priority) values(4, 'Bruno', 15);
insert into USER(id, name, priority) values(5, 'Olivier F.', 20);
insert into USER(id, name, priority) values(6, 'Olivier I.', 25);
insert into USER(id, name, priority) values(7, 'Laurent', 30);
insert into USER(id, name, priority) values(8, 'Edwige', 35);
insert into USER(id, name, priority) values(9, 'Stéphane', 40);
insert into USER(id, name, priority) values(10, 'Brice', 45);
insert into USER(id, name, priority) values(11, 'Frédérique', 50);
insert into USER(id, name, priority) values(12, 'Azzad', 55);
insert into USER(id, name, priority) values(13, 'Anthony', 60);
insert into USER(id, name, priority) values(14, 'Loïc', 65);
insert into USER(id, name, priority) values(15, 'Guillaume', 70);
insert into USER(id, name, priority) values(16, 'Ludovic', 75);
insert into USER(id, name, priority) values(17, 'Martin', 80);
insert into USER(id, name, priority) values(18, 'Lonny', 85);
insert into USER(id, name, priority) values(19, 'Hakim', 90);
insert into USER(id, name, priority) values(20, 'David', 95);

insert into PARKING_PLACE (id, numero, user_id) values (1, 255, 1);
insert into PARKING_PLACE (id, numero, user_id) values (2, 256, 2);
insert into PARKING_PLACE (id, numero, user_id) values (3, 257, 3);
insert into PARKING_PLACE (id, numero, user_id) values (4, 258, 4);
insert into PARKING_PLACE (id, numero, user_id) values (5, 259, 5);
insert into PARKING_PLACE (id, numero, user_id) values (6, 260, 6);
insert into PARKING_PLACE (id, numero, user_id) values (7, 262, 7);
insert into PARKING_PLACE (id, numero, user_id) values (8, 263, 8);
insert into PARKING_PLACE (id, numero, user_id) values (9, 264, 9);
insert into PARKING_PLACE (id, numero, user_id) values (10, 265, 10);
insert into PARKING_PLACE (id, numero, user_id) values (11, 266, 11);